export const SET_PRODUCTS = 'SET_PRODUCTS';
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';

export const ORDER_PRODUCT_LIST = 'ORDER_PRODUCT_LIST';