export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_PRODUCT = 'SET_PRODUCT';
export const FETCH_START = 'FETCH_START';
export const FETCH_FAILED = 'FETCH_FAILED';

export const ORDER_PRODUCT_LIST = 'ORDER_PRODUCT_LIST';

export const ADD_TO_SHOPPING_LIST = 'ADD_TO_SHOPPING_LIST';
